### ISSUE TITLE
Anki flashcard 404

### ISSUE THREAD

**Issue by arthurdouillard** [mtrazzi/understanding-the-RL-book#4]
Hey,

Thanks for the awesome repo.

Your google drive link to the anki flashcards is 404. Could you upload those on the anki plateform instead?

Thanks!

**Comment by mtrazzi** [comment]
Thanks for the heads up—updated the link in the README.

As for uploading on the anki platform, I'm afraid it might get deleted. 
> "If the deck you want to share is only of interest to a small group of people, please use the computer version to share it privately instead. Decks that receive very few downloads will be removed automatically."
